// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import CatcheditmodalController from "./catcheditmodal_controller"
application.register("catcheditmodal", CatcheditmodalController)

import CatchnewmapController from "./catchnewmap_controller"
application.register("catchnewmap", CatchnewmapController)

import CatchshowmapController from "./catchshowmap_controller"
application.register("catchshowmap", CatchshowmapController)

import CatchtogglemapController from "./catchtogglemap_controller"
application.register("catchtogglemap", CatchtogglemapController)

import CommentmodalController from "./commentmodal_controller"
application.register("commentmodal", CommentmodalController)

import DateController from "./date_controller"
application.register("date", DateController)

import DiaryeditmodalController from "./diaryeditmodal_controller"
application.register("diaryeditmodal", DiaryeditmodalController)

import DiarynewmapController from "./diarynewmap_controller"
application.register("diarynewmap", DiarynewmapController)

import DiaryshowmapController from "./diaryshowmap_controller"
application.register("diaryshowmap", DiaryshowmapController)

import DiarytogglemapController from "./diarytogglemap_controller"
application.register("diarytogglemap", DiarytogglemapController)

import FileUploadController from "./file_upload_controller"
application.register("file-upload", FileUploadController)

import FlashController from "./flash_controller"
application.register("flash", FlashController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import IntroController from "./intro_controller"
application.register("intro", IntroController)

import LikeController from "./like_controller"
application.register("like", LikeController)

import RecordController from "./record_controller"
application.register("record", RecordController)
