// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import DateController from "./date_controller"
application.register("date", DateController)

import EditmodalController from "./editmodal_controller"
application.register("editmodal", EditmodalController)

import FileUploadController from "./file_upload_controller"
application.register("file-upload", FileUploadController)

import FlashController from "./flash_controller"
application.register("flash", FlashController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import IntroController from "./intro_controller"
application.register("intro", IntroController)

import RecordController from "./record_controller"
application.register("record", RecordController)
